version: '2'

services:
    drupal:
        image: drupal:9.1.7
        restart: always
        ports: 
            - 8080:80
        volumes: 
            - drupal-modules:/var/www/html/modules
            - drupal-profiles:/var/www/html/profiles
            - drupal-sites:/var/www/html/sites
            - drupal-themes:/var/www/html/themes
        depends_on: 
            - postgres
    postgres:
        image: postgres:13.2
        restart: always
        environment: 
            POSTGRES_PASSWORD: pass
        volumes:
            - db-data:/var/lib/postgresql/data
volumes: 
    drupal-modules:
    drupal-profiles:
    drupal-sites:    
    drupal-themes:
    db-data:
